package it.unibz.pomodroid.factories;

import it.unibz.pomodroid.persistency.Activity;
import it.unibz.pomodroid.persistency.DBHelper;

import java.util.Date;
import java.util.HashMap;

public class ActivityFactory {
	// FIXME the method should not be static, please make it return the number of activities processed
	public static void produce (int id, Date deadLine, HashMap<String,String> attributes, DBHelper dbHelper){
		String auto = "AUTOGENERATED VALUE for ";
		if (attributes.get("description").equals("")) attributes.put("description", auto+"description.");
		if (attributes.get("summary").equals("")) attributes.put("summary", auto+"summary.");
		
		Activity activity = new Activity(0, new Date(), deadLine, attributes
				.get("summary").toString(), attributes.get("description")
				.toString(), "trac", id, attributes.get("priority").toString(),
				attributes.get("reporter").toString(), attributes.get("type")
						.toString());
		
		activity.save(dbHelper);
	}
	
}
