/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.xmlrpc;

public final class R {
    public static final class anim {
        public static final int push_left_in=0x7f040000;
        public static final int push_left_out=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int android=0x7f020000;
        public static final int error=0x7f020001;
        public static final int frame=0x7f020002;
    }
    public static final class id {
        public static final int params=0x7f060004;
        public static final int status=0x7f060000;
        public static final int tests=0x7f060002;
        public static final int text_result=0x7f060001;
        public static final int title=0x7f060003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int test=0x7f030001;
        public static final int text_view=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
